# Generated by Django 5.2.13 on 2026-04-25 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_vineyard_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(blank=True, default='', max_length=128)),
                ('processed_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PredictionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('prediction_weight', models.FloatField()),
                ('ground_truth_weight', models.FloatField(blank=True, null=True)),
                ('absolute_error', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(default='kg', max_length=32)),
                ('model', models.CharField(blank=True, default='', max_length=128)),
                ('depth_used', models.CharField(blank=True, max_length=512, null=True)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='api.predictionbatch')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
