# Generated by Django 5.2.13 on 2026-05-01 01:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('region', models.CharField(choices=[('napa', 'Napa'), ('sonoma', 'Sonoma'), ('burgundy', 'Burgundy'), ('bordeaux', 'Bordeaux'), ('mendoza', 'Mendoza'), ('other', 'Other')], default='other', max_length=20)),
                ('plan', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro')], default='free', max_length=10)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['region'], name='spray_org_region_cbaf7b_idx'), models.Index(fields=['created_at'], name='spray_org_created_8d79bb_idx')],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clerk_user_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('locale', models.CharField(default='en', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['email'], name='spray_user_email_b10c4f_idx'), models.Index(fields=['created_at'], name='spray_user_created_55102f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clerk_session_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('jwt_jti', models.CharField(blank=True, max_length=64)),
                ('device', models.CharField(blank=True, max_length=200)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='spray.user')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'revoked_at'], name='spray_sessi_user_id_0a6c74_idx'), models.Index(fields=['created_at'], name='spray_sessi_created_7408a0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('MEMBER', 'Member'), ('VIEWER', 'Viewer')], default='MEMBER', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='spray.org')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='spray.user')),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='spray_membe_user_id_6f4a5b_idx'), models.Index(fields=['org', 'role'], name='spray_membe_org_id_df4ac3_idx')],
                'constraints': [models.UniqueConstraint(fields=('org', 'user'), name='unique_org_user_membership')],
            },
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('photo_for_training', 'Use my photos and videos for ML training'), ('spray_records_for_benchmarks', 'Use my spray records for benchmarks'), ('anonymized_aggregates', 'Share anonymized aggregate insights'), ('marketing_email', 'Receive marketing email')], max_length=40)),
                ('granted', models.BooleanField(default=False)),
                ('granted_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_records', to='spray.user')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'category'], name='spray_conse_user_id_7b8ee8_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'category'), name='unique_user_category_consent')],
            },
        ),
        migrations.CreateModel(
            name='AuthEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('sign_up', 'Sign up'), ('email_verify', 'Email verify'), ('login_success', 'Login success'), ('login_failure', 'Login failure'), ('logout', 'Logout'), ('logout_all_devices', 'Logout from all devices'), ('password_change', 'Password change'), ('password_reset_requested', 'Password reset requested'), ('password_reset_completed', 'Password reset completed'), ('mfa_enable', 'MFA enable'), ('mfa_disable', 'MFA disable'), ('role_change', 'Role change'), ('org_created', 'Org created'), ('org_invite_sent', 'Org invite sent'), ('org_invite_accepted', 'Org invite accepted'), ('org_member_removed', 'Org member removed'), ('account_deletion_requested', 'Account deletion requested'), ('account_deletion_completed', 'Account deletion completed'), ('consent_granted', 'Consent granted'), ('consent_withdrawn', 'Consent withdrawn')], max_length=40)),
                ('outcome', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure')], default='success', max_length=10)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_events', to='spray.org')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_events', to='spray.user')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'created_at'], name='spray_authe_user_id_8bf420_idx'), models.Index(fields=['org', 'created_at'], name='spray_authe_org_id_e661a6_idx'), models.Index(fields=['type', 'created_at'], name='spray_authe_type_c9b7c0_idx')],
            },
        ),
    ]
