# Generated by Django 5.2.13 on 2026-05-06 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spray', '0006_capture'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='block',
            new_name='spray_block_vineyar_7843db_idx',
            old_name='spray_block_viney_idx',
        ),
        migrations.RenameIndex(
            model_name='block',
            new_name='spray_block_created_552413_idx',
            old_name='spray_block_created_idx',
        ),
        migrations.RenameIndex(
            model_name='capture',
            new_name='spray_captu_block_i_268e1b_idx',
            old_name='spray_cap_block_up_desc_idx',
        ),
        migrations.RenameIndex(
            model_name='capture',
            new_name='spray_captu_status_25c091_idx',
            old_name='spray_cap_status_created_idx',
        ),
        migrations.RenameIndex(
            model_name='datalakeevent',
            new_name='spray_datal_org_id_371d6d_idx',
            old_name='spray_dle_org_cat_idx',
        ),
        migrations.RenameIndex(
            model_name='datalakeevent',
            new_name='spray_datal_created_f08271_idx',
            old_name='spray_dle_created_idx',
        ),
        migrations.RenameIndex(
            model_name='externalriskindex',
            new_name='spray_exter_region_cba61a_idx',
            old_name='spray_eri_lookup_idx',
        ),
        migrations.RenameIndex(
            model_name='externalriskindex',
            new_name='spray_exter_pulled__101c6e_idx',
            old_name='spray_eri_pulled_idx',
        ),
        migrations.RenameIndex(
            model_name='vineyard',
            new_name='spray_viney_org_id_7fb8e9_idx',
            old_name='spray_viney_org_id_idx',
        ),
        migrations.RenameIndex(
            model_name='vineyard',
            new_name='spray_viney_created_74f9de_idx',
            old_name='spray_viney_created_idx',
        ),
        migrations.RenameIndex(
            model_name='weatherobservation',
            new_name='spray_weath_station_f5c4d2_idx',
            old_name='spray_wo_station_ts_desc_idx',
        ),
        migrations.RenameIndex(
            model_name='weatherstation',
            new_name='spray_weath_org_id_a710fc_idx',
            old_name='spray_ws_org_idx',
        ),
        migrations.RenameIndex(
            model_name='weatherstation',
            new_name='spray_weath_region_8392e2_idx',
            old_name='spray_ws_region_default_idx',
        ),
        migrations.AlterField(
            model_name='datalakeevent',
            name='payload',
            field=models.JSONField(default=dict),
        ),
    ]
