# Generated by Django 5.2.13 on 2026-05-13 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spray', '0007_rename_spray_block_viney_idx_spray_block_vineyar_7843db_idx_and_more'),
        ('spray', '0010_spray_record'),
    ]

    operations = [
    ]
