# Generated by hand — widen block.geom to MultiPolygon for merged footprints.

from django.contrib.gis.db.models import MultiPolygonField
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("spray", "0011_merge_20260513_2258"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    """
                    ALTER TABLE spray_block
                    ALTER COLUMN geom TYPE geometry(MultiPolygon,4326)
                    USING ST_Multi(ST_Force2D(geom));
                    """,
                    reverse_sql="""
                    ALTER TABLE spray_block
                    ALTER COLUMN geom TYPE geometry(Polygon,4326)
                    USING ST_GeometryN(geom, 1);
                    """,
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name="block",
                    name="geom",
                    field=MultiPolygonField(srid=4326),
                ),
            ],
        ),
    ]
