# Generated by Django 5.2.13 on 2026-05-14 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spray', '0012_block_geom_multipolygon'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='blockverdict',
            new_name='spray_block_block_i_159112_idx',
            old_name='spray_bv_block_date_idx',
        ),
        migrations.RenameIndex(
            model_name='blockverdict',
            new_name='spray_block_action_761ce8_idx',
            old_name='spray_bv_action_date_idx',
        ),
        migrations.RenameIndex(
            model_name='integrationconnection',
            new_name='spray_integ_org_id_a9bbb8_idx',
            old_name='spray_ic_org_vendor_status_idx',
        ),
        migrations.RenameIndex(
            model_name='integrationconnection',
            new_name='spray_integ_status_d9f9e2_idx',
            old_name='spray_ic_status_connectedat_idx',
        ),
        migrations.RenameIndex(
            model_name='oauthstate',
            new_name='spray_oauth_expires_08edfa_idx',
            old_name='spray_oauth_expires_idx',
        ),
        migrations.RenameIndex(
            model_name='oauthstate',
            new_name='spray_oauth_org_id_603850_idx',
            old_name='spray_oauth_org_vendor_idx',
        ),
        migrations.RenameIndex(
            model_name='riskrecord',
            new_name='spray_riskr_block_i_bf75f9_idx',
            old_name='spray_rr_block_validfrom_idx',
        ),
        migrations.RenameIndex(
            model_name='riskrecord',
            new_name='spray_riskr_pathoge_d70031_idx',
            old_name='spray_rr_pathogen_validfrom_idx',
        ),
        migrations.RenameIndex(
            model_name='riskrecord',
            new_name='spray_riskr_model_i_bb7913_idx',
            old_name='spray_rr_model_validfrom_idx',
        ),
        migrations.RenameIndex(
            model_name='sensorreading',
            new_name='spray_senso_station_6d7570_idx',
            old_name='spray_sr_station_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='sensorreading',
            new_name='spray_senso_quality_ebaf25_idx',
            old_name='spray_sr_quality_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='sensorstation',
            new_name='spray_senso_connect_ca0f96_idx',
            old_name='spray_ss_conn_lastseen_idx',
        ),
        migrations.RenameIndex(
            model_name='sprayrecord',
            new_name='spray_spray_block_i_a43359_idx',
            old_name='spray_spray_block_applied_idx',
        ),
        migrations.RenameIndex(
            model_name='sprayrecord',
            new_name='spray_spray_target__bb8b8d_idx',
            old_name='spray_spray_target_applied_idx',
        ),
        migrations.RenameIndex(
            model_name='sprayrecord',
            new_name='spray_spray_archive_448044_idx',
            old_name='spray_spray_arch_created_idx',
        ),
    ]
