# Generated by Django 5.2.13 on 2026-05-15 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spray', '0014_blockpowderymildewindex'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='blockpowderymildewindex',
            new_name='spray_block_block_i_3fd86f_idx',
            old_name='spray_bpmi_block_date_idx',
        ),
        migrations.AlterField(
            model_name='blockpowderymildewindex',
            name='phase',
            field=models.CharField(choices=[('inactive', 'Inactive'), ('active', 'Active')], max_length=16),
        ),
        migrations.AlterField(
            model_name='blockpowderymildewindex',
            name='risk_tier',
            field=models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], max_length=16),
        ),
    ]
