# Generated by Django 5.2.13 on 2026-05-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spray', '0017_vine'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='vine',
            new_name='spray_vine_block_i_c42c2e_idx',
            old_name='spray_vine_block__b8e2a1_idx',
        ),
        migrations.RenameIndex(
            model_name='vine',
            new_name='spray_vine_block_i_d9b1a2_idx',
            old_name='spray_vine_block__a4f3c2_idx',
        ),
        migrations.AlterField(
            model_name='vine',
            name='vine_index',
            field=models.PositiveIntegerField(help_text='Position along the row (1 = headland start).'),
        ),
    ]
