# Generated by Django 5.2.13 on 2026-04-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_predictionbatch_predictionresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionresult',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='prediction_uploads/%Y/%m/%d'),
        ),
    ]
