# Generated by Django 5.2.13 on 2026-05-15 07:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_predictionresult_image'),
        ('spray', '0015_newsroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsroomAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('can_publish', models.BooleanField(default=True)),
                ('can_manage_permissions', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newsroom_grants_given', to='spray.user')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='newsroom_access', to='spray.user')),
            ],
            options={
                'verbose_name_plural': 'Newsroom access grants',
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('excerpt', models.TextField(blank=True, default='', max_length=2000)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='news_articles', to='spray.user')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['status', '-published_at'], name='api_newsart_status_0e03aa_idx')],
            },
        ),
    ]
