# Generated by Django 5.2.13 on 2026-05-16 19:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_newsroom'),
        ('spray', '0018_rename_spray_vine_block__b8e2a1_idx_spray_vine_block_i_c42c2e_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsroomaccess',
            name='can_publish',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='news_uploads/%Y/%m/%d')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_news_images', to='spray.user')),
            ],
        ),
    ]
