# Generated by Django 5.2.13 on 2026-05-16 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_newsroomaccess_can_publish_newsimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsroomaccess',
            name='can_publish',
            field=models.BooleanField(default=True),
        ),
    ]
