release: python manage.py migrate --noinput && python manage.py collectstatic --noinput
web: python manage.py migrate --noinput && python manage.py collectstatic --noinput && gunicorn graft_api.wsgi --bind 0.0.0.0:${PORT:-8080} --log-file - --capture-output --error-logfile -
