// @graft/client-core/api
//
// OpenAPI-generated client for the Graft Spray API.
//
// Empty at M0-01. Generated by openapi-typescript-codegen from
// services/api/openapi.yaml in M0-04. Re-runs on every API change.

export {};
